### ISSUE TITLE
How to do GPU frame capture  on Windows?

### ISSUE THREAD

**Issue by ychding11** [nvpro-samples/gl_dynamic_lod#1]

**Comment by ghost** [comment]
Hi Yaochuang,

Thanks for asking! There are a couple of GPU frame debuggers you can use to capture frames on Windows for a variety of graphics APIs; since gl_dynamic_lod is a Vulkan application, here's how to use Nsight Graphics (which can also capture frames from D3D11, D3D12, OpenGL, and Vulkan applications, and has lots of other neat features) to capture a frame after building the application:

- From the project selection screen that appears after you launch Nsight Graphics, select "Continue" under Quick Launch:
![image](https://user-images.githubusercontent.com/1071701/61233861-6b09bd00-a6e6-11e9-981f-9ba4277f35c5.png)

- In the Launch tab in the "Connect to process" window, set the Application Executable path to the path of the gl_dynamic_lod executable you built (the default CMake script puts this in the parent directory of the gl_dynamic_lod directory as of this writing):
![image](https://user-images.githubusercontent.com/1071701/61234239-698cc480-a6e7-11e9-83c7-b69cb3219c8a.png)
You can leave the Working Directory field blank; make sure Automatically Connect is set to Yes in this case (since otherwise you'll have to manually connect after waiting for the application to start).

- Depending on whether you're more interested in debugging or profiling frames at the moment, select the "Frame Debugger" or "Frame Profiler" activity in the Activity section, then press "Launch" to have Nsight launch the application.
![image](https://user-images.githubusercontent.com/1071701/61234460-f899dc80-a6e7-11e9-9a3b-aa829cf43642.png)

- You should now see gl_dynamic_lod appear a bit like this - you can see some frame timing and histogram information in the heads-up display that appears to let you know that Nsight is connected:
![image](https://user-images.githubusercontent.com/1071701/61234526-2b43d500-a6e8-11e9-98ec-23fe9300c405.png)

- In the main Nsight Graphics Window, you can then click "Capture for Live Analysis" in the main toolbar to capture a frame and pause the application:
![image](https://user-images.githubusercontent.com/1071701/61234595-50d0de80-a6e8-11e9-8f06-e5425b6b7b29.png)

- Once you've done that, you can scrub through API events, view textures and resources as they change through the frame, view geometry, look at timing and profiling information, export as a C++ capture, and more:
![image](https://user-images.githubusercontent.com/1071701/61234707-a5745980-a6e8-11e9-8fa7-98a4cdc0f5e4.png)

For more information, please see the [Nsight Graphics Documentation and Support page](https://developer.nvidia.com/nsight-graphics-documentation-and-support), or feel free to ask on the [Nsight Graphics forum](https://devtalk.nvidia.com/default/board/322/nsight-graphics/). I'm going to go ahead and close this issue.

**Comment by ychding11** [comment]
OK, Thanks! I got it.
